//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPhotography_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string CategoryName { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string GroomName { get; set; }
        public string BrideName { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Total { get; set; }
        public string Discount { get; set; }
        public string Price { get; set; }
        public string Paid { get; set; }
        public string Carry { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public string Time { get; set; }
    }
}
